response/result.rs: Replace generate_deserialize_metadata macro with a function
wprzytula/scylla-rust-driver pull request #3
Opened 2024-10-25 13:58 UTC by Lorak-mmk

This macro is unnecessary, function is enough here. For ease of future development, lets get rid of such macros.

## Pre-review checklist

- [ ] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [ ] I added relevant tests for new features and bug fixes.
- [ ] All commits compile, pass static checks and pass test.
- [ ] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have provided docstrings for the public items that I want to introduce.
- [ ] I have adjusted the documentation in `./docs/source/`.
- [ ] I added appropriate `Fixes:` annotations to PR description.

2024-10-25 15:22 UTC, Lorak-mmk commented
v2: Moved `deserialize_metadata_generic` to `impl RawMetadataAndRawRows` and made it a private method.

2024-10-26 19:50 UTC, wprzytula requested changes
Huge thanks for this!

2024-10-26 19:50 UTC, wprzytula commented on scylla-cql/src/frame/response/result.rs
> +    /// Deserializes ResultMetadata in the form mentioned by its name,
No longer true - the name does not mention the form.

2024-10-26 19:50 UTC, wprzytula commented on scylla-cql/src/frame/response/result.rs
> +                //$use_cached_metadata(cached)
leftover commented out code

2024-10-28 09:01 UTC, Lorak-mmk commented
Rebased

2024-10-28 09:02 UTC, merged